language: python
python: 3.5
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=hg35
    - TOXENV=hg36
    - TOXENV=hg41
    - TOXENV=hg42
    - TOXENV=coverage
install: pip install docutils tox
script: tox
